# Auto-generated by scripts/advanced/01-setup-backend.sh - safe to delete.
# Deleting this file and re-running 'terraform init' switches back to local state.
terraform {
  backend "s3" {
    bucket         = "thermos-terraform-state-076586969151"
    key            = "terraform-docker/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "thermos-terraform-locks"
    encrypt        = true
  }
}
