#!/usr/bin/env bash
# =============================================================================
# 01-setup-backend.sh - OPTIONAL: bootstrap remote Terraform state (S3 +
#                        DynamoDB) and wire it into BOTH terraform-docker/
#                        and terraform-eks/
#
# This is a "Level 2" script - the core workshop (RUNBOOK.md) works fine
# without it, using local state. Run this first if you want to practice the
# remote-state pattern used in real team projects. See
# docs/09-remote-terraform-state.md.
#
# What it does:
#   1. terraform apply's the small bootstrap config in terraform-docker/backend/
#      (creates ONE S3 bucket + ONE DynamoDB table, shared by both modules)
#   2. Writes terraform-docker/backend.tf AND terraform-eks/backend.tf, each
#      pointing at that same bucket/table but with its own state "key" so
#      the two modules' state files never collide:
#        - terraform-docker/terraform.tfstate
#        - terraform-eks/terraform.tfstate
#   3. Re-initializes whichever of those two modules already has local state
#      to migrate it into the new remote backend. A module you haven't
#      applied yet (no terraform.tfstate / .terraform/ present) is simply
#      initialized fresh against the new backend - there's nothing to migrate.
#
# Usage: ./scripts/advanced/01-setup-backend.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
BACKEND_DIR="${PROJECT_ROOT}/terraform-docker/backend"
DOCKER_DIR="${PROJECT_ROOT}/terraform-docker"
EKS_DIR="${PROJECT_ROOT}/terraform-eks"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() { echo -e "\n${BLUE}================================${NC}\n${BLUE}$1${NC}\n${BLUE}================================${NC}\n"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_info()    { echo -e "${YELLOW}ℹ️  $1${NC}"; }

print_header "Setting up remote Terraform state (S3 + DynamoDB)    < 1 min approximately"

command -v terraform >/dev/null 2>&1 || { echo "terraform not found - run ./scripts/01-setup.sh first"; exit 1; }
aws sts get-caller-identity >/dev/null 2>&1 || { echo "AWS credentials not configured - run 'aws configure' first"; exit 1; }

# NOTE: backend.tf always exists in terraform-docker/ and terraform-eks/ as an
# inactive, fully-commented template (see each file's own header) - so we
# can't just check for its existence. We check for an actual, ACTIVE
# (uncommented) 'backend "s3"' block instead.
is_backend_active() {
  local backend_file="$1"
  [ -f "$backend_file" ] && grep -qE '^\s*backend\s+"s3"\s*\{' "$backend_file"
}

if is_backend_active "${DOCKER_DIR}/backend.tf" && is_backend_active "${EKS_DIR}/backend.tf"; then
  print_info "Both terraform-docker/backend.tf and terraform-eks/backend.tf already have an"
  print_info "active S3 backend - remote state is already set up for both modules."
  print_info "Run ./scripts/advanced/05-destroy-backend.sh first if you want to recreate it."
  exit 0
fi

print_info "Creating S3 bucket + DynamoDB lock table (terraform-docker/backend/)..."
cd "$BACKEND_DIR"
terraform init -input=false
terraform apply -auto-approve -input=false

BUCKET="$(terraform output -raw bucket_name)"
TABLE="$(terraform output -raw dynamodb_table_name)"
REGION="$(terraform output -raw region)"

print_success "Created bucket: $BUCKET"
print_success "Created lock table: $TABLE"

write_backend_tf_and_init() {
  local module_dir="$1"   # e.g. terraform-docker
  local module_name="$2"  # e.g. terraform-docker (used as the state key prefix)
  local backend_file="${module_dir}/backend.tf"

  if is_backend_active "$backend_file"; then
    print_info "${module_name}/backend.tf already has an active S3 backend - leaving it as is."
    return
  fi

  print_info "Writing ${backend_file} ..."
  cat > "$backend_file" <<EOF
# Auto-generated by scripts/advanced/01-setup-backend.sh - safe to delete.
# Deleting this file and re-running 'terraform init' switches back to local state.
terraform {
  backend "s3" {
    bucket         = "${BUCKET}"
    key            = "${module_name}/terraform.tfstate"
    region         = "${REGION}"
    dynamodb_table = "${TABLE}"
    encrypt        = true
  }
}
EOF
  print_success "Wrote ${backend_file}"

  print_info "Re-initializing ${module_name}/ to use the new remote backend..."
  cd "$module_dir"
  if [ -f "terraform.tfstate" ] || [ -d ".terraform" ]; then
    # Existing local state to migrate into S3.
    terraform init -input=false -migrate-state -force-copy
  else
    # Nothing applied yet in this module - just point it at the new backend.
    terraform init -input=false
  fi
}

write_backend_tf_and_init "$DOCKER_DIR" "terraform-docker"
write_backend_tf_and_init "$EKS_DIR" "terraform-eks"

print_header "Remote state is ready"
echo "From now on, every script in scripts/ and scripts/advanced/ that runs"
echo "Terraform (03-deploy.sh, 07-destroy.sh, 02-eks-up.sh, 04-k8s-destroy.sh)"
echo "will automatically use this S3 backend - no changes needed to any of them."
echo ""
print_info "To tear this down at the end of your session (AFTER destroying BOTH the main"
print_info "infrastructure with ./scripts/07-destroy.sh AND, if you used it, EKS with"
print_info "./scripts/advanced/04-k8s-destroy.sh), run: ./scripts/advanced/05-destroy-backend.sh"
