#!/usr/bin/env bash
# =============================================================================
# 06-ssh.sh — SSH into the deployed EC2 instance
#
# WHAT THIS DOES:
#   Reads the EC2 public IP and the auto-generated SSH key path from Terraform
#   outputs, then opens an SSH connection. You do NOT need to remember the
#   IP address or hunt for the .pem file.
#
# HOW IT FINDS THE KEY:
#   1. Checks Terraform output `ssh_private_key_path`
#   2. Checks environment variable THERMOS_SSH_KEY
#   3. Falls back to prompting you
#
# HOW LONG: Instant.
#
# USAGE:
#   ./scripts/06-ssh.sh                    # auto-detect everything
#   ./scripts/06-ssh.sh /path/to/key.pem   # explicit key path
#   THERMOS_SSH_KEY=/path/to/key.pem ./scripts/06-ssh.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="${PROJECT_ROOT}/terraform-docker"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_error()   { echo -e "${RED}❌ $1${NC}"; }
print_info()    { echo -e "${YELLOW}ℹ️  $1${NC}"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_header()  { echo -e "\n${BLUE}================================${NC}\n${BLUE}$1${NC}\n${BLUE}================================${NC}\n"; }

print_header "Thermos 06-ssh: SSH Connection"

if [ ! -d "$TERRAFORM_DIR" ]; then
  print_error "Terraform directory not found: $TERRAFORM_DIR"
  exit 1
fi

cd "$TERRAFORM_DIR"

# Get EC2 IP
EC2_IP="$(terraform output -raw ec2_public_ip 2>/dev/null || true)"
if [ -z "$EC2_IP" ]; then
  print_error "Could not read ec2_public_ip from Terraform output."
  print_info "Run ./scripts/03-deploy.sh first."
  exit 1
fi
print_info "EC2 Instance IP: $EC2_IP"

# Determine key path
KEY_PATH="${1:-${THERMOS_SSH_KEY:-}}"

if [ -z "$KEY_PATH" ]; then
  AUTO_KEY="$(terraform output -raw ssh_private_key_path 2>/dev/null || true)"
  if [ -n "$AUTO_KEY" ] && [ -f "$AUTO_KEY" ]; then
    KEY_PATH="$AUTO_KEY"
    print_success "Auto-detected key: $KEY_PATH"
  fi
fi

if [ -z "$KEY_PATH" ]; then
  print_info "Could not auto-detect the SSH key."
  print_info "The key is usually at: ${TERRAFORM_DIR}/thermos-key.pem"
  read -r -p "Enter the full path to your .pem key file: " KEY_PATH
fi

# Expand tilde
KEY_PATH="${KEY_PATH/#\~/$HOME}"

if [ ! -f "$KEY_PATH" ]; then
  print_error "Key file not found: $KEY_PATH"
  print_info ""
  print_info "The SSH key is generated by Terraform during deploy and saved to:"
  print_info "  ${TERRAFORM_DIR}/thermos-key.pem"
  print_info ""
  print_info "If you ran deploy from a different machine, copy the key first:"
  print_info "  scp <other-machine>:/path/to/terraform-docker/thermos-key.pem ./"
  print_info ""
  print_info "Or run the manual SSH command:"
  print_info "  ssh -i ${TERRAFORM_DIR}/thermos-key.pem ubuntu@${EC2_IP}"
  exit 1
fi

# Fix permissions if needed
CURRENT_MODE="$(stat -c '%a' "$KEY_PATH" 2>/dev/null || stat -f '%Lp' "$KEY_PATH" 2>/dev/null || echo "")"
if [ -n "$CURRENT_MODE" ] && [ "$CURRENT_MODE" != "600" ] && [ "$CURRENT_MODE" != "400" ]; then
  print_info "Fixing key file permissions (chmod 600)"
  chmod 600 "$KEY_PATH"
fi

print_success "Connecting to ubuntu@${EC2_IP} ..."
print_info "(Type 'exit' or press Ctrl+D to disconnect)"
exec ssh -o StrictHostKeyChecking=accept-new -i "$KEY_PATH" "ubuntu@${EC2_IP}"
