# =============================================================================
# backend.tf — Remote State Backend (S3 + DynamoDB)
# =============================================================================
# This file is generated by scripts/advanced/01-setup-backend.sh
# DO NOT edit manually. To use remote state:
#   1. Run: ./scripts/advanced/01-setup-backend.sh
#   2. Uncomment the backend block below
#   3. Run: terraform init -migrate-state
# =============================================================================

# terraform {
#   backend "s3" {
#     bucket         = "thermos-terraform-state-<your-account-id>"
#     key            = "terraform-eks/terraform.tfstate"
#     region         = "us-east-1"
#     encrypt        = true
#     dynamodb_table = "thermos-terraform-locks"
#   }
# }
